<h1>Detail objednávky <?php echo $this->order['customOrderId'] ?></h1>

<h2><?=$this->escape($this->order['productName']);?></h2>

<table class="table table-bordered" style="width: 250px">
<tr>
	<td colspan="2"><?=$this->escape($this->order['productDescription']);?></td>
</tr>
<tr>
	<th>Bodová hodnota</th>
	<td><?=round($this->order['orderCredits']/$this->order['orderAmount']);?></td>
</tr>
<tr>
	<th>Počet kusů</th>
	<td><?=$this->escape($this->order['orderAmount']);?></td>
</tr>
<tr>
	<th>Cena v bodech</th>
	<td><?=$this->escape($this->order['orderCredits']);?></td>
</tr>
<? if (isset($this->warehouseKeeperView)) { ?>
<tr>
	<th>Zaměstnanec</th>
	<td><?=$this->escape($this->order['employeeName']);?></td>
</tr>
<? } ?>
<tr>
	<th>Datum objednání</th>
	<td><?=($this->order['orderInserted']->format('m.d.Y H:i'));?></td>
</tr>
<tr>
	<th>Poslední změna</th>
	<td>
            <?php if (!empty($this->order['statusChanged'])): ?>
                <?=($this->order['statusChanged']->format('m.d.Y H:i'));?>
            <?php else: ?>
                 - 
            <?php endif ?>
        </td>
</tr>
<tr>
	<th>Stav objednávky</th>
	<td><?=$this->escape($this->order['orderStatusName']);?></td>
</tr>
<?php if ($this->order['stornoReason']): ?>
<tr>
	<th>Důvod stornování</th>
	<td><?=$this->escape($this->order['stornoReason']);?></td>
</tr>
<?php endif ?>
</table>

<?php if (isset($this->displayConfirm)): ?>
<a class="btn btn-primary" id="confirmbtn" href="<?php echo $this->url(array('action' => 'confirm', 'id' => $this->order['orderId'])) ?>">Potvrdit objednávku</a>
<?php endif ?>

<?php if (isset($this->displayPrepare)): ?>

<?php if ($this->enough): ?>
Zboží je skladem <?php echo $this->stock ?>

<a class="btn btn-primary" id="preparebtn" href="<?php echo $this->url(array('action' => 'prepare', 'id' => $this->order['orderId'])) ?>">Potvrdit k převzetí</a>

<?php else: ?>
Zboží není skladem
<?php endif ?>




<?php endif ?>


<?php if ($this->order['orderCancellable']): ?>
    <a class="btn btn-danger order-cancelButton" id="cancelbtn" href="<?php echo $this->url(array('action' => 'cancel', 'id' => $this->order['orderId'])) ?>?<?=$this->ask? "employee=true": "";?>">Storno</a>
<?php endif ?>

<?if ($this->ask) { ?>
<script type="text/javascript">
    $(function() {
        $(".order-cancelButton").bind("click", function() {
            return confirm("Opravdu stornovat?");
        });
    });
</script>
<?}?>