<?
    $orderList = $this->userOrderList ?: $this->warehouseKeeperOrderList;
?>

<h1>Objednávky</h1>

<table class="table">
<tr>
    <th>Zboží</th>
    <? if ($this->warehouseKeeperOrderList) { ?>
    <th>Zaměstnanec</th>
    <? } ?>
    <th>Datum objednání</th>
    <th>Cena v bodech</th>
    <th>Stav objednávky</th>
    <th>Akce</th>
</tr>

<? if ($orderList) { ?>
<? foreach($orderList as $order) { ?>
<tr>
    <td><?=$this->escape($order['productName']);?></td>
    <? if ($this->warehouseKeeperOrderList) { ?>
    <td><?//TODO;?></td>
    <? } ?>
    <td><?=($order['orderInserted']->format('m. d. Y '));?></td>
    <td><?=$this->escape($order['orderCredits']);?></td>
    <td><?=$this->escape($order['orderStatusName']);?></td>
    <td><a class="btn" href="<?php echo $this->url(array('action' => 'edit', 'id' => @$order['id'])) ?>"><i class="icon-edit"></i> Detail</a></td>
</tr>
<? } ?>
<? } else { ?>
<tr>
    <td style="font-style:italic" colspan="<?=$this->userOrderList? 6 : 5 ?>">Žádné objednávky.</td>
</tr>
<? } ?>
</table>
