<?
    $orderList = $this->userOrderList ?: $this->warehouseKeeperOrderList;
?>

<h1>Objednávky</h1>

<table class="table table-bordered" style="margin-top:20px">
<tr>
    <th>Zboží</th>
    <? if ($this->warehouseKeeperOrderList) { ?>
    <th>Zaměstnanec</th>
    <? } ?>
    <th>Datum objednání</th>
    <th>Cena v bodech</th>
    <th>Stav objednávky</th>
    <th></th>
</tr>

<? if ($orderList) { ?>
<? foreach($orderList as $order) { ?>
<tr>
    <td>
        <a href="./orders/detail?id=<?=$order['orderId'];?>"> <?//TODO: ta adresa ne tak natvrdo tady?>
            <?=$this->escape($order['productName']);?>
        </a>
    </td>
    <? if ($this->warehouseKeeperOrderList) { ?>
    <td><?=$this->escape($order['orderEmployeeName']);?></td>
    <? } ?>
    <td><?=($order['orderInserted']->format('m. d. Y '));?></td>
    <td><?=$this->escape($order['orderCredits']);?></td>
    <td><?=$this->escape($order['orderStatusName']);?></td>
    <td>
		<? if ($order['orderCancellable']) { ?>
        <a href="./orders/detail?id=<?=$order['orderId'];?>" class="btn btn-danger">Storno</a> <?//TODO: ta adresa ne tak natvrdo tady?>
		<? } ?>
    </td>
</tr>
<? } ?>
<? } else { ?>
<tr>
    <td style="font-style:italic" colspan="<?=$this->userOrderList? 6 : 5 ?>">Žádné objednávky.</td>
</tr>
<? } ?>
</table>
