
<h1>Objednávky</h1>

<table class="tablesorter">
<thead>
    <tr>
    <th>Zboží</th>
    <?php if (isset($this->warehouser)): ?>
    <th>Zaměstnanec</th>
    <?php endif ?>
    <th>Datum objednání</th>
    <th>Cena v bodech</th>
    <th>Stav objednávky</th>
    <th>Akce</th>
</tr>
</thead>
<tbody>

<?php if ($this->list) { ?>
<?php foreach($this->list as $order) { ?>
<tr>
    <td>
         <?=$this->escape($order['productName']);?>
    </td>
    <?php if (isset($this->warehouser)): ?>
    <td><?= $this->escape($order['orderEmployeeName']);?></td>
    <?php endif ?>
    <td><?= $order['orderInserted']->format('d.m.y H:i');?></td>
    <td><?= $this->escape($order['orderCredits']);?></td>
    <td><?= $this->escape($order['orderStatusName']);?></td>
    <td>
		<?php if ($order['orderCancellable']): ?>
        <a href="<?php echo $this->url(array('action' => 'cancel', 'id' => $order['orderId'])) ?>?<?=$this->ask? "employee=true": "";?>" class="btn btn-danger order-cancelButton">Storno</a>
		<?php endif ?>
        <a class="btn" href="<?php echo $this->url(array('action' => 'detail', 'id' => $order['orderId'])) ?>?<?=$this->ask? "employee=true": "";?>"><i class="icon-edit"></i> Detail</a>
    </td>
</tr>
<?php } ?>
<?php } else { ?>
<tr>
    <td style="font-style:italic" colspan="<?=isset($this->warehouser) ? 6 : 5 ?>">Žádné objednávky.</td>
</tr>
<?php } ?>
</tbody>
</table>

<?if ($this->ask) { ?>
<script type="text/javascript">
    $(function() {
        $(".order-cancelButton").bind("click", function() {
            return confirm("Opravdu stornovat?");
        });
    });
</script>
<?}?>


<script type="text/javascript">
    
    $(document).ready(function() { 
    $("table").tablesorter({ 
        sortList: [[0,0]] 
    }); 
}); 
    
    </script>