<ul>

    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>">Homepage</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'import', 'action' => 'index')) ?>">Obnovit tovární nastavení</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>?login=admin@intrashop">Přihlásit jako vedoucí pracovník</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>?login=jan.novak@intrashop">Přihlásit jako běžný zaměstnanec</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>?login=warehouser@intrashop">Přihlásit jako správce skladu</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')) ?>?login=personnel@intrashop">Přihlásit jako personalista</a></li>
    
    
</ul>