<h1>Přidělit mimořádné body</h1>

<table class="table table-bordered" style="margin-top:20px">
<tr>
    <th>Jméno zaměstnance</th>
    <th>Oddělení</th>
</tr>
<? foreach ($this->employeeList as $employee) { ?>
<tr>
    <td><a href="extra-credits-admin/add?userId=<?=$employee['employeeId'];?>"><?=$this->escape($employee['employeeName']);?></a></th>
    <td><?=$employee['departmentName'];?></td>
</tr>
<? } ?>
</table>
