<?php echo $this->doctype() ?>
<html>
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headMeta() ?>
    <!-- Le styles -->
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl() ?>/css/styles.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="http://tablesorter.com/themes/blue/style.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl() ?>/css/tablesort.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/favicon.ico">
    
    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/jquery.tablesorter.min.js"></script>
    
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Intrashop</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'index')) ?>">Obchod</a></li>
              <li><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'catalog')) ?>">Katalog zboží</a></li>
              <li><a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'orders')) ?>">Objednávky</a></li>
            </ul>
            <?
                switch ($this->role) {
                    case 'Employee':
                        $role = 'zaměstnanec';
                        break;

                    case 'PersonnelOfficer':
                        $role = 'personalista';
                        break;

                    case 'WarehouseKeeper':
                        $role = 'správce skladu';
                        break;
                }
            ?>
            <p class="navbar-text pull-right">
                Přihlášen jako <?=$role;?> <a href="#"><?php echo $this->username ?>
           </a>
                | <span class="credits"><?php echo $this->balance ?> bodů</span>
            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
            <?php if ($this->layout()->info): ?>
            <ul class="unstyled"  style="border: 1px solid; border-color: lightblue">
            <?php foreach ($this->layout()->info as $info): ?>
            
            <li>
            <i class="icon-info-sign"></i>
            
            <?php echo $this->escape($info) ?>
            
            </li>

            <?php endforeach ?>
                </ul>
            <?php endif ?>
            
            
        <?php echo $this->layout()->content ?>
          
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; 4IT442 2012</p>
      </footer>

    </div><!--/.fluid-container-->


  </body>
</html>


