<?php echo $this->doctype() ?>
<html>
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headMeta() ?>
    <!-- Le styles -->
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl() ?>/css/styles.css" rel="stylesheet">
    <style type="text/css">
    </style>
    <!--link href="http://tablesorter.com/themes/blue/style.css" rel="stylesheet"-->
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl() ?>/css/tablesort.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/favicon.ico">

    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/jquery.tablesorter.min.js"></script>

    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url(array('action' => 'index', 'controller' => 'index'), null, true) ?>">
              <img src="http://images2.wikia.nocookie.net/__cb20080519060532/egamia/images/thumb/d/d9/Umbrella_Corporation_logo.gif/50px-Umbrella_Corporation_logo.gif" alt="" width="20" />
              Intrashop</a>
          <div class="nav-collapse">
              <?php echo $this->navigation()->menu()->setMaxDepth(0)->setUlClass('nav') ?>
              <p class="navbar-text pull-right">
                <?php echo $this->username ?>

                | <span class="credits"><?php echo $this->balance ?> bodů</span>
                <? if ($this->personnelOfficerBalance !== null) { ?>
                | <span class="credits"><?=$this->personnelOfficerBalance;?> mimořádných bodů</span>
                <? } ?>
                <? if ($this->superiorEmployeeBalance !== null) { ?>
                | <span class="credits"><?=$this->superiorEmployeeBalance;?> výkonových bodů</span>
                <? } ?>

                |
                <a href="<?php echo $this->url(array('action' => 'logout', 'controller' => 'index')) ?>">Odhlásit</a>
            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">

              <?php echo $this->navigation()->menu()->renderSubMenu(null, 'nav nav-list') ?>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
            <?= $this->partial('messages.phtml', $this) ?>

        <?php echo $this->layout()->content ?>



      </div><!--/row-->

      <br style="clear: both;">

      <footer>
          <hr>
        <p>&copy; 4IT442 2012</p>
      </footer>

    </div><!--/.fluid-container-->
  </body>
</html>


