<h1>Přidělit výkonové body</h1>

<h2 style=" margin-top: 20px;"><?=$this->escape($this->employeeInfo['employeeName']);?></h2>
<table class="table table-bordered" style="width: 200px;">
<tr>
	<th>Funkce</th>
	<td><?=$this->escape($this->employeeInfo['functionName']);?></td>
</tr>
</table>

<?=$this->adminForm;?>

<? if($this->showConfirmDialog) { ?>
<script type="text/javascript">
$(function() {
	if(confirm('Skutečně přidělit?')) {
		$('#hiddenconfirm').val('true');
		$('#buttondetail').click();
	}
})
</script>
<? } ?>
