<h1>Katalog zboží</h1>
        <div id="products">
        <?php foreach ($this->products as $product): ?>
        
            
        <div class="product">
            <h3>
            <?php echo $this->escape($product->getCode()) ?>     
            <?php echo $this->escape($product->getName()) ?>            
            </h3>
            
            <p>
            <?php echo nl2br($this->escape($product->getDescription())) ?>
                </p>
            
            <img src="<?php echo $this->pictureUri($product->getPicture()) ?>" width="200" alt="" />
            
            <p><br /><a class="btn" href="<?php echo $this->url(array('action' => 'index', 'controller' => 'product', 'id' => $product->getId())) ?>">Zobrazit &raquo;</a></p>
        </div>
        
        <?php endforeach; ?>
</div>

