<div class="hero-unit">
            <h1>Intrashop</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
          </div>

 
        <div id="products">
        <?php foreach ($this->products as $product): ?>
        
            
        <div class="product">
            <h2>
            <?php echo $this->escape($product->getCode()) ?>     
            <?php echo $this->escape($product->getName()) ?>            
            </h2>
            
            <p>
            <?php echo nl2br($this->escape($product->getDescription())) ?>
                </p>
            
            <img src="<?php echo $product->getPicture() ?>" width="200" alt="" />
            <p><a class="btn" href="<?php echo $this->url(array('action' => 'index', 'controller' => 'product', 'id' => $product->getId())) ?>">View details &raquo;</a></p>
        </div>
        
        <?php endforeach; ?>
</div>

